---
title: 'Class 6: R functions'
author: "Tianhao Qiu"
date: "4/18/2019"
output: html_document
editor_options: 
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About 
This is my **class 6** r markdown document with my *code* and notes for the day.

```{r}
plot(1:10, typ = "l", col = "blue")
```

```{r}
read.table("test1.txt", header = TRUE, sep = ",")
```

```{r}
read.csv("test1.txt")
```

```{r}
read.csv("test2.txt", sep = "$")
```

```{r}
read.table("test3.txt")
```

```{r}
read.table("https://bioboot.github.io/bimm143_S19/class-material/test2.txt", header = TRUE, sep = "$")
```

## Functions

Our first silly function example:
```{r}
add <- function (x, y = 1) {
  x + y 
}
```

```{r}
add(10)
add(10,10)
add(x = 1, y = 4)
add(c(1,2,3))
add(c(1,2,3), 4)
```

```{r}
# add(1,2,3)
```

```{r}
rescale <- function(x, noNull = TRUE, plot = FALSE) {
  rng <-range(x, na.rm = noNull)
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
rescale(c(1,2,3,4,NA))
```

```{r}
rescale2 <- function(x, na.rm = TRUE, plot = FALSE) {
  rng <-range(x, na.rm = na.rm)
  print("Hello")
  
  if (!is.numeric(x)) {
    return("垃圾")
    #stop("S")
  } 
  answer <- (x - rng[1]) / (rng[2] - rng[1])
    
  print("is it me you are looking for?")
   
  if (plot) {
    plot(answer, typ="b", lwd=4)
    print("哈哈哈哈哈哈哈哈哈")
  }
   
  print("I can see it in ...")
  return(answer)
}
```

```{r}
rescale2(c(1,3,NA,10), plot = TRUE)
rescale2(c(1,2,3,"s"))
```

```{r}
x <- c(1,2,3, "s")
is.numeric(x)
```

